name: Google Java Format
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master, main, develop]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Run Google Java Format
        run: mvn spotless:apply
